# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('q_p_0', models.CharField(max_length=1000)),
                ('q_p_1', models.CharField(max_length=1000)),
                ('q_p', models.CharField(max_length=1000)),
                ('p_0', models.FloatField()),
                ('p_1', models.FloatField()),
                ('p', models.FloatField()),
                ('ig', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amt_key', models.TextField()),
                ('query_target_mean', models.BooleanField()),
                ('target_mean', models.FloatField()),
                ('target_question', models.TextField()),
                ('status', models.TextField(default='created')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_started', models.DateField(blank=True)),
                ('date_finished', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.Job'),
        ),
    ]
