# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='target_question',
            new_name='target_mean_question',
        ),
    ]
