# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20170223_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='query_target_mean',
            field=models.BooleanField(default=False),
        ),
    ]
