# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_auto_20170223_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='path_crowd_answers',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
