# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0008_job_path_crowd_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=20)),
                ('answer', models.FloatField()),
                ('type', models.CharField(max_length=8)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.Feature')),
            ],
        ),
    ]
