# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0009_crowdanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='path_questions',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='Estimation Job', max_length=100),
        ),
    ]
