# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0010_auto_20170227_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('fullquery', models.TextField(blank=True, db_column='fullQuery', null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('fullanswer', models.TextField(blank=True, db_column='fullAnswer', null=True)),
                ('paymentcents', models.IntegerField(blank=True, db_column='paymentCents', null=True)),
                ('fullproperties', models.TextField(blank=True, db_column='fullProperties', null=True)),
                ('questioncreationdate', models.DateTimeField(blank=True, db_column='questionCreationDate', null=True)),
                ('questionanswerdate', models.DateTimeField(blank=True, db_column='questionAnswerDate', null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='createDate', null=True)),
                ('answeruser', models.CharField(blank=True, db_column='answerUser', max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'queries',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='is_target',
            field=models.BooleanField(default=False),
        ),
    ]
