# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0011_auto_20170227_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='path_out_crowd_answers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='path_out_feature_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
